mvc-ska/Models/Account.cs
using System.ComponentModel.DataAnnotations;

namespace mvc_ska.Models;

public class Account
{
    public int Id { get; set; }
    [Range(0, 1E+17)]
    public decimal Amount { get; set; }
    [Required]
    public DateTime Date { get; set; }
    [Required]
    public string Remark { get; set; }
}

mvc-ska/Models/ErrorViewModel.cs
namespace mvc_ska.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

mvc-ska/Models/ViewModels/AccountView.cs
namespace mvc_ska.Models.ViewModels;

public class AccountView
{
    public Account Account { get; set; }
    public List<Account> Accounts { get; set; }
}

mvc-ska/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using mvc_ska.Models;
using mvc_ska.Models.ViewModels;
using mvc_ska.services;
namespace mvc_ska.Controllers;

[Route("[controller]")]
public class AccountController : Controller
{
    private readonly AccountService _accountService;
    public AccountController(AccountService accountService)
    {
        _accountService = accountService;
    }
    [HttpGet]
    public IActionResult Index()
    {
        AccountView model = new AccountView()
        {
            Account = new Account(),
            Accounts = _accountService.accounts
        };
        return View(model);
    }
    
    [HttpPost]
    public IActionResult CreatePartial(Account account)
    {
        AccountView model = new AccountView()
        {
            Account = account, 
            Accounts = _accountService.accounts
        };
        if (!ModelState.IsValid)
        {
            return View( "Index", model);
        }
        
        account.Id = _accountService.nextId++;
        _accountService.accounts.Add(account);
        return View("Index", model);
    }
}

mvc-ska/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvc_ska.Models;

namespace mvc_ska.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

mvc-ska/Controllers/api/RecordController.cs
using Microsoft.AspNetCore.Mvc;
using mvc_ska.services;

namespace mvc_ska.Controllers.api.v1;

[Route("api")]
public class RecordController : Controller
{
    private readonly AccountService _accountService;
    public RecordController(AccountService accountService)
    {
        _accountService = accountService;
    }
    
    [HttpGet("records")]
    public IActionResult Records()
    {
        return Ok(_accountService.accounts);
    }
}

mvc-ska/Controllers/api/v1/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using mvc_ska.services;

namespace mvc_ska.Controllers.api.v1;

[Route("api/v1/[controller]")]
public class AccountController : Controller
{
    private readonly AccountService _accountService;
    public AccountController(AccountService accountService)
    {
        _accountService = accountService;
    }
    
    [HttpGet("list")]
    public IActionResult List()
    {
        return Ok(_accountService.accounts);
    }
}

mvc-ska/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

mvc-ska/Views/Record/CreatePartial.cshtml
@model Account

<form asp-controller="Record" asp-action="CreatePartial" method="post">
    <table>
        <tr>
            <td>Amount</td>
            <td><input asp-for="Amount" /></td>
            <td>
               @Html.ValidationMessageFor(model => model.Amount) 
            </td>
        </tr>
        <tr>
            <td>Remark</td>
            <td><input asp-for="Remark" /></td>
            <td>
                @Html.ValidationMessageFor(model => model.Remark)
            </td>
        </tr>
        <tr>
            <td>Date</td>
            <td><input asp-for="Date" type="date" /></td>
            <td>
                @Html.ValidationMessageFor(model => model.Date)
            </td>
        </tr>
        <tr>
            <td></td>
            <td><button>Submit</button></td>
        </tr>
    </table>
</form>

mvc-ska/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - mvc_ska</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/mvc_ska.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc_ska</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - mvc_ska - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>